name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]

jobs:
  check_comments:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
    - name: Slash Command Dispatch - Repo - Write
      uses: peter-evans/slash-command-dispatch@v3
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      with:
        issue-type: pull-request
        permission: write
        commands: |
          land
