name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]

jobs:
  check_comments:
    runs-on: ubuntu-latest
    steps:
      if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/land') }}
      - name: Show Environment Variables
        run: env
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Show Github Object
        run: |
          cat <<'EOF'
          ${{ toJson(github) }}
          EOF
      - name: Show Github Event Path Json
        run: 'cat $GITHUB_EVENT_PATH || true'
      - uses: actions/checkout@v3
        with:
          token: $${{ steps.app-token.outputs.token }}
          fetch-depth: '0'
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Check Current CI Status
        run: |
          pip install requests ghstack
          .github/workflows/scripts/ghstack-perm-check.py <<'EOF'
          ${{ toJson(github) }}
          EOF
        env:
          GITHUB_TOKEN: $${{ steps.app-token.outputs.token }}
      - name: Land It!
        run: |
          git config --global user.email "horace@thinkingmachines.ai"
          git config --global user.name "ghstack bot"
          cat <<EOF > ~/.ghstackrc
          [ghstack]
          github_url = github.com
          github_oauth = $GITHUB_TOKEN
          github_username = chillee
          remote_name = origin
          EOF
          ghstack land "${{ github.event.client_payload.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: $${{ steps.app-token.outputs.token }}

      # - uses: actions/create-github-app-token@v1
      #   id: app-token
      #   with:
      #     app-id: ${{ vars.APP_ID }}
      #     private-key: ${{ secrets.PRIVATE_KEY }}
      # - name: Slash Command Dispatch - Repo - Write
      #   uses: peter-evans/slash-command-dispatch@v3
      #   with:
      #     token: $${{ steps.app-token.outputs.token }}
      #     # reaction-token: $${{ steps.app-token.outputs.token }}
      #     issue-type: pull-request
      #     permission: write
      #     commands: |
      #       land
